<?php
namespace common\models;

use common\common\ErrDesc;
use yii\db\ActiveRecord;

class Classification extends ActiveRecord {

    public static function tableName()
    {
        return '{{%qq_classification}}';
    }

    public function rules()
    {
        //return parent::rules(); // TODO: Change the autogenerated stub
        return [
            [['class_name', 'parent_id', 'other_name'],'safe']
        ];
    }

    public function validateAdd()
    {
        if(empty($this->class_name)) {
            return ErrDesc::ERR_PARAM;
        }
        if(empty($this->parent_id))
            $this->parent_id = -1;
        return ErrDesc::OK;
    }


    public static function getChildren($parent_id)
    {
        $children = self::findAll(['parent_id' => $parent_id]);
        return $children;
    }

    public static function getMenu()
    {
        return self::find()->asArray()->all();

    }

    public function validateDel()
    {
        if(empty($this->class_id))
            return ErrDesc::ERR_PARAM;
        return ErrDesc::OK;
    }

    public static function del($class_id)
    {
        $child = self::getChildren($class_id);
        if(!empty($child)) {
            return ErrDesc::ERR_MENU_CHILD;
        }
        self::find()->where(['class_id' => $class_id])->one()->delete();
        return ErrDesc::OK;
    }
}


