<?php
/**
 * Created by PhpStorm.
 * User: xxh
 * Date: 2017/9/15
 * Time: 8:39
 */
namespace common\models;

use yii\db\ActiveRecord;

class OriginPlace extends ActiveRecord {

    public static function tableName()
    {
        return '{{%qq_origin_place}}';
    }

    public function rules()
    {
        //return parent::rules(); // TODO: Change the autogenerated stub
        return [
            [['origin_place_name'], 'required'],
            [['top_class_id','second_class_id'], 'safe']
        ];
    }
}