<?php
namespace common\models;

use yii\db\ActiveRecord;

class ShoppingCart extends ActiveRecord {

    public static function tableName()
    {
        return '{{%qq_shopping_cart}}';
    }

    public static function primaryKey()
    {
        //return parent::primaryKey(); // TODO: Change the autogenerated stub
        return ['user_id', 'product_id'];
    }
}