<?php
/**
 * Created by PhpStorm.
 * User: xxh
 * Date: 2017/9/15
 * Time: 10:08
 */
namespace common\models;

use yii\db\ActiveRecord;

class Standard extends ActiveRecord {

    public static function tableName()
    {
        return '{{%qq_standard}}';
    }

    public function rules()
    {
        //return parent::rules(); // TODO: Change the autogenerated stub
        return [
            [['standard_name'], 'required'],
        ];
    }
}