<?php

namespace common\models;

use common\common\ErrDesc;
use common\common\QQMongo;
use yii\db\ActiveRecord;

class User extends ActiveRecord {

    const SCENARIO_LOGIN = 'login';
    const SCENARIO_REGISTER = 'register';

    public $ckpassword;
    public $verify_phone_code;

    public static function tableName()
    {
        return '{{%qq_user}}';
    }

    public function scenarios()
    {
        //return parent::scenarios(); // TODO: Change the autogenerated stub
        return [
            self::SCENARIO_LOGIN => ['user_phone', 'user_passwd'],
            self::SCENARIO_REGISTER => ['user_phone', 'user_passwd', 'ckpassword', 'verify_phone_code'],
        ];
    }

    public function rules()
    {
        //return parent::rules(); // TODO: Change the autogenerated stub
        return [
            [['user_phone', 'user_passwd'], 'required', 'on'=>self::SCENARIO_LOGIN],
            [['user_phone', 'user_passwd', 'ckpassword', 'verify_phone_code'], 'required', 'on'=>self::SCENARIO_REGISTER],
        ];
    }

    public function validateRegister()
    {
        if($this->validate()) {
            if($this->user_passwd != $this->ckpassword) {
                return ErrDesc::ERR_CK_PWD;
            }
            $vfcode = QQMongo::getVerifyCode($this->user_phone);
            if($vfcode != $this->verify_phone_code) {
                return ErrDesc::ERR_VERIFY_CODE;
            }
            $user = self::findOne(['user_phone' => $this->user_phone]);
            if(!empty($user)) {
                return ErrDesc::ERR_PHONE_EXIST;
            }
            $this->user_passwd = md5($this->user_passwd);
            return ErrDesc::OK;
        }
        return ErrDesc::ERR_PARAM;
    }

    public function validateLogin()
    {
        if($this->validate()) {
            $this->user_passwd = md5($this->user_passwd);
            $user = self::findOne(['user_phone'=>$this->user_phone, 'user_passwd'=>$this->user_passwd]);
            if(empty($user)) {
                return ErrDesc::ERR_PHONE_PASSWD;
            }
            \Yii::$app->session['user_phone'] = $user->user_id;
            return ErrDesc::OK;
        }
        return ErrDesc::ERR_PARAM;
    }
}