<?php
namespace common\controllers;

use common\common\ErrDesc;
use yii\web\Controller;

class QQBaseController extends Controller {
    public $enableCsrfValidation = false;
    public $layout = 'qingqing';
    public $requestData;

    public function beforeAction($action)
    {
        $this->requestData = array_merge(\Yii::$app->request->get(), \Yii::$app->request->post());
        if(array_key_exists('r', $this->requestData))
            unset($this->requestData['r']);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function rtJson($code=ErrDesc::OK, $data=[])
    {
        $rtMsg = [
            'code' => $code,
            'msg' => ErrDesc::$DESC[$code],
            'data' => $data
        ];
        return $this->asJson($rtMsg);
    }

    public function getClientParam($param, $default='')
    {
        if(array_key_exists($param, $this->requestData )) {
            if(is_array($this->requestData[$param]))
                return $this->requestData[$param];
            return trim($this->requestData[$param]);
        }
        return $default;
    }
}